# ----------------------------------------
# WordPress Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      nodePort: {{ .Values.wordpress.service.nodePort }}
  selector:
    app: wordpress

---
# ----------------------------------------
# WordPress Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
          ports:
            - containerPort: 80
              name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mariadb.user }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mariadb.dbName }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass-secret
                  key: mariadb-password
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_HOME', 'http://{{ .Values.ingress.host }}:{{ .Values.wordpress.service.nodePort }}');
                define('WP_SITEURL', 'http://{{ .Values.ingress.host }}:{{ .Values.wordpress.service.nodePort }}');
          
          # Kaynak sınırları (Hiyerarşi düzeltildi)
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          # Probe tanımları (Tekrar kaldırıldı ve typo düzeltildi)
          livenessProbe:
            httpGet:
              path: /readme.html
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readme.html
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3

          # Volume mount (Hiyerarşi düzeltildi)
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
      
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc

---
# ----------------------------------------
# WordPress PVC
# ----------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.pvc.storage }}
