apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: wordpress-runner-deploy
  namespace: actions-runner-system
spec:
  template:
    spec:
      repository: colak-inanc/c4n
      env:
        - name: DOCKER_INSECURE_REGISTRY
          value: {{ .Values.harbor.url | quote }}
      dockerVolumeMounts:
        - name: docker-config
          mountPath: /etc/docker/daemon.json
          subPath: daemon.json
      volumes:
        - name: docker-config
          configMap:
            name: harbor-insecure-config
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: wordpress-runner-as
  namespace: actions-runner-system
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    name: wordpress-runner-deploy
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'    
    scaleDownThreshold: '0.30'
